name: course_search_environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.9
  - conda-forge::faiss
  - conda-forge::sentence-transformers
  - conda-forge::pickle5
  - numpy
  - pandas
  - pip
  - pip:
    - streamlit-analytics
    - faiss